name: Test Packages Windows

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node: ['14', '16']
    name: Build with Node ${{ matrix.node }}
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: 🏗 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 120000
      - name: 👷 Build packages
        run: yarn lerna run prepare --stream
      - name: ✅ Lint packages
        run: yarn lint --max-warnings=0
      - name: 🗂 Upload builds
        uses: actions/cache@v3
        with:
          path: '*'
          key: v2-${{ github.sha }}-${{ matrix.node }}
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        node: ['14', '16']
        package:
          [
            dev-tools,
            babel-preset-cli,
            config,
            config-plugins,
            dev-server,
            expo-cli,
            expo-codemod,
            image-utils,
            json-file,
            metro-config,
            package-manager,
            pkcs12,
            plist,
            pwa,
            schemer,
            uri-scheme,
            webpack-config,
            xdl,
          ]
    name: Test ${{ matrix.package }} on Node ${{ matrix.node }}
    steps:
      - name: 🗂 Download builds
        uses: actions/cache@v3
        with:
          path: '*'
          key: v2-${{ github.sha }}-${{ matrix.node }}
      - name: 🏗 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: 🧪 Test ${{ matrix.package }}
        run: cd packages/${{ matrix.package }} && yarn test
        # run: cd packages/${{ matrix.package }} && yarn test --coverage
        env:
          CI: true
          EXPO_DEBUG: true
