name: Test Packages

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16']
    name: Build with Node ${{ matrix.node }}
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: 🏗 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile --check-files
      - name: 👷 Build packages
        run: yarn lerna run prepare --stream
      - name: ✅ Lint packages
        run: yarn lint --max-warnings=0
      - name: 🗂 Upload builds
        uses: actions/cache@v3
        with:
          path: '*'
          key: v2-${{ github.sha }}-${{ matrix.node }}
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        node: ['14', '16']
        package:
          [
            dev-tools,
            babel-preset-cli,
            config,
            config-plugins,
            dev-server,
            expo-cli,
            expo-codemod,
            image-utils,
            json-file,
            metro-config,
            package-manager,
            prebuild-config,
            pkcs12,
            plist,
            pwa,
            schemer,
            uri-scheme,
            webpack-config,
            xdl,
          ]
    name: Test ${{ matrix.package }} on Node ${{ matrix.node }}
    steps:
      - name: 🗂 Download builds
        uses: actions/cache@v3
        with:
          path: '*'
          key: v2-${{ github.sha }}-${{ matrix.node }}
      - name: 🏗 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: 🧪 Test ${{ matrix.package }}
        # run: cd packages/${{ matrix.package }} && yarn test
        run: cd packages/${{ matrix.package }} && yarn test --coverage
        env:
          CI: true
          EXPO_DEBUG: true
      - name: 🔍 Find test flag
        id: cov-flag-name
        run: echo "::set-output name=flag::$(echo ${{ matrix.package }} | perl -pe 's/[^a-z]+([a-z])/\U\1/gi;s/^([A-Z])/\l\1/')"
      - name: 🕵️ Analyze test coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./packages/${{ matrix.package }}/coverage/clover.xml # optional
          flags: ${{ steps.cov-flag-name.outputs.flag }} # optional
          fail_ci_if_error: false # optional (default = false)

  puppeteer:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
    name: Expo Webpack
    steps:
      - name: 🗂 Download builds
        uses: actions/cache@v2
        with:
          path: '*'
          key: v2-${{ github.sha }}-${{ matrix.node }}
      - name: 🏗 Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: yarn
      - name: 📦 Install puppeteer
        working-directory: packages/webpack-config
        run: yarn add -D puppeteer@3.1.0
      - name: 📦 Install dependencies
        working-directory: packages/webpack-config/e2e/basic
        run: yarn
      # Test starting an Expo web project
      - name: 🧪 Test starting Webpack
        working-directory: packages/webpack-config
        run: yarn test:e2e:start
        env:
          CI: true
      # Test building an Expo web project
      - name: 🧪 Test building Webpack
        working-directory: packages/webpack-config
        run: yarn test:e2e:build
        env:
          CI: true
